-- DROP DATABASE IF EXISTS new_database;
DROP TABLE IF EXISTS public."UTENTE" CASCADE;
CREATE TABLE public."UTENTE" (
	"ID" serial NOT NULL,
	"Nome" varchar(20) NOT NULL,
	"Cognome" varchar(20) NOT NULL,
	"Email" varchar(35) NOT NULL,
	"Telefono" varchar(10),
	"Password" varchar(64),
	"ID_INDIRIZZO" integer NOT NULL,
	CONSTRAINT "UTENTE_pk" PRIMARY KEY ("ID")
);
DROP TABLE IF EXISTS public."INDIRIZZO" CASCADE;
CREATE TABLE public."INDIRIZZO" (
	"ID" serial NOT NULL,
	"Via" varchar(60) NOT NULL,
	"Città" varchar(30) NOT NULL,
	"Cap" varchar(5) NOT NULL,
	"Provincia" varchar(2) NOT NULL,
	"Regione" varchar(21) NOT NULL,
	CONSTRAINT "INDIRIZZO_pk" PRIMARY KEY ("ID")
);
DROP TABLE IF EXISTS public."ORDINE" CASCADE;
CREATE TABLE public."ORDINE" (
	"NumOrdine" serial NOT NULL,
	"Data" date NOT NULL,
	"ID_UTENTE" integer NOT NULL,
	"ID_INDIRIZZO" integer NOT NULL,
	"Nome_CODICE SCONTO" varchar(12),
	CONSTRAINT "ORDINE_pk" PRIMARY KEY ("NumOrdine")
);
DROP TABLE IF EXISTS public."GRUPPO TASTIERE" CASCADE;
CREATE TABLE public."GRUPPO TASTIERE" (
	"ID" serial NOT NULL,
	"NumOrdine_ORDINE" integer NOT NULL,
	"ID_TASTIERA MECCANICA" integer NOT NULL,
	CONSTRAINT "GRUPPO TASTIERE_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."GRUPPO TASTIERE" DROP CONSTRAINT IF EXISTS "ORDINE_fk" CASCADE;
ALTER TABLE public."GRUPPO TASTIERE"
ADD CONSTRAINT "ORDINE_fk" FOREIGN KEY ("NumOrdine_ORDINE") REFERENCES public."ORDINE" ("NumOrdine") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."KEYCAPS" CASCADE;
CREATE TABLE public."KEYCAPS" (
	"ID" serial NOT NULL,
	"Materiale" varchar(40) NOT NULL,
	"Designer" varchar(40) NOT NULL,
	"Shine_through" bool NOT NULL,
	"Profilo" varchar(6) NOT NULL,
	"Manufacturer" varchar(20) NOT NULL,
	"Prezzo" money NOT NULL,
	"Quantità" smallint NOT NULL,
	"ID_LAYOUT" integer NOT NULL,
	CONSTRAINT "KEYCAPS_pk" PRIMARY KEY ("ID")
);
DROP TABLE IF EXISTS public."LAYOUT" CASCADE;
CREATE TABLE public."LAYOUT" (
	"ID" serial NOT NULL,
	"Formato" varchar(7) NOT NULL,
	"Size" varchar(4) NOT NULL,
	"N_tasti" smallint NOT NULL,
	CONSTRAINT "LAYOUT_pk" PRIMARY KEY ("ID")
);
DROP TABLE IF EXISTS public."TASTIERA MECCANICA" CASCADE;
CREATE TABLE public."TASTIERA MECCANICA" (
	"ID" serial NOT NULL,
	"ID_KEYCAPS" integer NOT NULL,
	"ID_PCB" integer NOT NULL,
	"ID_SWITCH" smallint NOT NULL,
	"ID_PLATE" integer NOT NULL,
	"ID_CASE" integer NOT NULL,
	CONSTRAINT "MECHANICAL KEYBOARD_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."TASTIERA MECCANICA" DROP CONSTRAINT IF EXISTS "KEYCAPS_fk" CASCADE;
ALTER TABLE public."TASTIERA MECCANICA"
ADD CONSTRAINT "KEYCAPS_fk" FOREIGN KEY ("ID_KEYCAPS") REFERENCES public."KEYCAPS" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."PCB" CASCADE;
CREATE TABLE public."PCB" (
	"ID" serial NOT NULL,
	"Pin_number" smallint NOT NULL,
	"Manufacturer" varchar(20) NOT NULL,
	"Ports" varchar(11) NOT NULL,
	"Hotswappable" bool NOT NULL,
	"Retroilluminazione" bool NOT NULL,
	"Prezzo" money NOT NULL,
	"Quantità" smallint NOT NULL,
	"Capacità_batteria" smallint,
	"ID_LAYOUT" integer NOT NULL,
	CONSTRAINT "PCB_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."TASTIERA MECCANICA" DROP CONSTRAINT IF EXISTS "PCB_fk" CASCADE;
ALTER TABLE public."TASTIERA MECCANICA"
ADD CONSTRAINT "PCB_fk" FOREIGN KEY ("ID_PCB") REFERENCES public."PCB" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."SWITCH" CASCADE;
CREATE TABLE public."SWITCH" (
	"ID" smallint NOT NULL,
	"Colore" varchar(20),
	"Actuation_force" smallint,
	"Transparenza" bool,
	"Led_facing" varchar(5),
	"Silent" bool,
	"Pin_number" smallint,
	"Manufacturer" varchar(20),
	"Actuation_type" varchar(7),
	"Prezzo" money,
	CONSTRAINT "SWITCH_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."TASTIERA MECCANICA" DROP CONSTRAINT IF EXISTS "SWITCH_fk" CASCADE;
ALTER TABLE public."TASTIERA MECCANICA"
ADD CONSTRAINT "SWITCH_fk" FOREIGN KEY ("ID_SWITCH") REFERENCES public."SWITCH" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."PLATE" CASCADE;
CREATE TABLE public."PLATE" (
	"ID" serial NOT NULL,
	"Materiale" varchar(40) NOT NULL,
	"Manufacturer" varchar(20) NOT NULL,
	"Prezzo" money NOT NULL,
	"Quantità" smallint NOT NULL,
	"ID_LAYOUT" integer NOT NULL,
	CONSTRAINT "PLATE_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."TASTIERA MECCANICA" DROP CONSTRAINT IF EXISTS "PLATE_fk" CASCADE;
ALTER TABLE public."TASTIERA MECCANICA"
ADD CONSTRAINT "PLATE_fk" FOREIGN KEY ("ID_PLATE") REFERENCES public."PLATE" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."CASE" CASCADE;
CREATE TABLE public."CASE" (
	"ID" serial NOT NULL,
	"Colore" varchar(20),
	"Materiale" varchar(20) NOT NULL,
	"Manufacturer" varchar(20) NOT NULL,
	"Prezzo" money NOT NULL,
	"Quantità" smallint NOT NULL,
	"ID_LAYOUT" integer NOT NULL,
	CONSTRAINT new_table_pk PRIMARY KEY ("ID")
);
-- ALTER TABLE public."TASTIERA MECCANICA" DROP CONSTRAINT IF EXISTS "CASE_fk" CASCADE;
ALTER TABLE public."TASTIERA MECCANICA"
ADD CONSTRAINT "CASE_fk" FOREIGN KEY ("ID_CASE") REFERENCES public."CASE" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."KEYCAPS" DROP CONSTRAINT IF EXISTS "LAYOUT_fk" CASCADE;
ALTER TABLE public."KEYCAPS"
ADD CONSTRAINT "LAYOUT_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES public."LAYOUT" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."PCB" DROP CONSTRAINT IF EXISTS "LAYOUT_fk" CASCADE;
ALTER TABLE public."PCB"
ADD CONSTRAINT "LAYOUT_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES public."LAYOUT" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."CASE" DROP CONSTRAINT IF EXISTS "LAYOUT_fk" CASCADE;
ALTER TABLE public."CASE"
ADD CONSTRAINT "LAYOUT_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES public."LAYOUT" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."PLATE" DROP CONSTRAINT IF EXISTS "LAYOUT_fk" CASCADE;
ALTER TABLE public."PLATE"
ADD CONSTRAINT "LAYOUT_fk" FOREIGN KEY ("ID_LAYOUT") REFERENCES public."LAYOUT" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."UTENTE" DROP CONSTRAINT IF EXISTS "INDIRIZZO_fk" CASCADE;
ALTER TABLE public."UTENTE"
ADD CONSTRAINT "INDIRIZZO_fk" FOREIGN KEY ("ID_INDIRIZZO") REFERENCES public."INDIRIZZO" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."ORDINE" DROP CONSTRAINT IF EXISTS "UTENTE_fk" CASCADE;
ALTER TABLE public."ORDINE"
ADD CONSTRAINT "UTENTE_fk" FOREIGN KEY ("ID_UTENTE") REFERENCES public."UTENTE" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."ORDINE" DROP CONSTRAINT IF EXISTS "INDIRIZZO_fk" CASCADE;
ALTER TABLE public."ORDINE"
ADD CONSTRAINT "INDIRIZZO_fk" FOREIGN KEY ("ID_INDIRIZZO") REFERENCES public."INDIRIZZO" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."GRUPPO TASTIERE" DROP CONSTRAINT IF EXISTS "TASTIERA MECCANICA_fk" CASCADE;
ALTER TABLE public."GRUPPO TASTIERE"
ADD CONSTRAINT "TASTIERA MECCANICA_fk" FOREIGN KEY ("ID_TASTIERA MECCANICA") REFERENCES public."TASTIERA MECCANICA" ("ID") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."CODICE SCONTO" CASCADE;
CREATE TABLE public."CODICE SCONTO" (
	"Nome" varchar(12) NOT NULL,
	"Valore" money NOT NULL,
	CONSTRAINT "CODICE SCONTO_pk" PRIMARY KEY ("Nome")
);
-- ALTER TABLE public."ORDINE" DROP CONSTRAINT IF EXISTS "CODICE SCONTO_fk" CASCADE;
ALTER TABLE public."ORDINE"
ADD CONSTRAINT "CODICE SCONTO_fk" FOREIGN KEY ("Nome_CODICE SCONTO") REFERENCES public."CODICE SCONTO" ("Nome") MATCH FULL ON DELETE
SET NULL ON UPDATE CASCADE;
DROP TABLE IF EXISTS public."RECENSIONE" CASCADE;
CREATE TABLE public."RECENSIONE" (
	"ID" smallint NOT NULL,
	"Valutazione" varchar(1) NOT NULL,
	"Data" date NOT NULL,
	"Testo" varchar(140),
	"NumOrdine_ORDINE" integer NOT NULL,
	CONSTRAINT "RECENSIONE_pk" PRIMARY KEY ("ID")
);
-- ALTER TABLE public."RECENSIONE" DROP CONSTRAINT IF EXISTS "ORDINE_fk" CASCADE;
ALTER TABLE public."RECENSIONE"
ADD CONSTRAINT "ORDINE_fk" FOREIGN KEY ("NumOrdine_ORDINE") REFERENCES public."ORDINE" ("NumOrdine") MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE;
-- ALTER TABLE public."RECENSIONE" DROP CONSTRAINT IF EXISTS "RECENSIONE_uq" CASCADE;
ALTER TABLE public."RECENSIONE"
ADD CONSTRAINT "RECENSIONE_uq" UNIQUE ("NumOrdine_ORDINE");
